import './globals.css'
import Navbar from '../components/Navbar'

export const metadata = {
  title: 'Jeff | Full-Stack Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='relative'>
        <Navbar />
        <div>{children}</div>
      </body>
    </html>
  )
}
