import './globals.css'
import Providers from "./providers"

export const metadata = {
  title: 'Jeff Hwang | Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='relative'>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
